config/routes.rb
Blog::Application.routes.draw do
  resources :follows

  resources :alluserblogs, :only => [:index]

  resources :users do  #one user has many blogs
    resources :userblogs 
  end 

  resources :userblogs do  #one user has many blogs
    resources :entries 
  end 

  resources :entries 

  root :to => 'home#index'

end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  content     :text
#  userblog_id :integer
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Entry < ActiveRecord::Base
  belongs_to :userblog
  attr_accessible :content, :title, :userblog_id
  
  validates :title, :presence => true 

  validates :title, :uniqueness => { :scope => :userblog_id }  
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id

  belongs_to :follower, :class_name => "User", :foreign_key => 'follower_id'

  belongs_to :followed, :class_name => "User", :foreign_key => 'followed_id'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  location   :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :location, :userblog_id
  has_many :userblogs
  has_many :follow
  
end

app/models/userblog.rb
# == Schema Information
#
# Table name: userblogs
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :string(255)
#  user_id     :integer
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Userblog < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :title, :user_id
  validates_presence_of :user_id
  has_many :entries 
end

app/controllers/alluserblogs_controller.rb
class AlluserblogsController < ApplicationController

  def index
    @userblogs = Userblog.all
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
 
  def index
    #raise params.to_yaml

    @entries = Entry.find_all_by_userblog_id(params[:userblog_id])
    @userblog = Userblog.find(params[:userblog_id]) 
    
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @userblog = Userblog.find(params[:userblog_id]) 
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    #raise params.to_yaml 
    @entry = Entry.new(params[:entry])
    @entry.save
    redirect_to userblog_entries_path(params[:userblog_id]), notice: 'Entry was successfully created.' 
  end


  def update
    @entry = Entry.find(params[:id])
    @entry.update_attributes(params[:entry])

    redirect_to userblog_entry_path(@entry.userblog_id,@entry.id), notice: 'Userblog was successfully updated.' 
  end

 
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  # GET /follows
  # GET /follows.json
  def index
    @follows = Follow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @follows }
    end
  end

  # GET /follows/1
  # GET /follows/1.json
  def show
    @follow = Follow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follow }
    end
  end

  # GET /follows/new
  # GET /follows/new.json
  def new
    @follow = Follow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follow }
    end
  end

  # GET /follows/1/edit
  def edit
    @follow = Follow.find(params[:id])
  end

  # POST /follows
  # POST /follows.json
  def create
    @follow = Follow.new(params[:follow])

    respond_to do |format|
      if @follow.save
        format.html { redirect_to @follow, notice: 'Follow was successfully created.' }
        format.json { render json: @follow, status: :created, location: @follow }
      else
        format.html { render action: "new" }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /follows/1
  # PUT /follows/1.json
  def update
    @follow = Follow.find(params[:id])

    respond_to do |format|
      if @follow.update_attributes(params[:follow])
        format.html { redirect_to @follow, notice: 'Follow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.json
  def destroy
    @follow = Follow.find(params[:id])
    @follow.destroy

    respond_to do |format|
      format.html { redirect_to follows_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@now = Time.now	
  end
end

app/controllers/userblogs_controller.rb
class UserblogsController < ApplicationController

  def index
    @userblogs = Userblog.find_all_by_user_id(params[:user_id]) 
    #raise params.inspect
    @user = User.find(params[:user_id])
    # raise @user.inspect 
  end

  def show
    #raise params.inspect
    @userblog = Userblog.find(params[:id])
    @user = User.find(params[:user_id])

  end

  def new
    #raise params.inspect
    @user = User.find(params[:user_id])

  end

  def edit
    @userblog = Userblog.find(params[:id])
  end


  def create
    #raise params.inspect
    #@userblog = params[:userblog]
    #raise @userblog.inspect
    
    @userblog = Userblog.new(params[:userblog])
    @userblog.save

    redirect_to user_userblog_path(@userblog.user_id,@userblog.id), notice: 'Userblog was successfully created.' 

  end

  def update
    # raise params.inspect
    @userblog = Userblog.find(params[:id])
    @userblog.update_attributes(params[:userblog])

    redirect_to user_userblog_path(@userblog.user_id,@userblog.id), notice: 'Userblog was successfully updated.' 
       
  end

  def destroy
    @userblog = Userblog.find(params[:id])
    @userblog.destroy
    
    redirect_to user_userblogs_path(@userblog.user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

  
  end

  def show
    @user = User.find(params[:id])

  end

  def new
    @user = User.new


  end

  def edit
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(params[:user])

    @user.save
    
    redirect_to users_path , notice: 'User was successfully created.' 
  
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

  
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/userblogs_helper.rb
module UserblogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/alluserblogs/index.html.erb
<h1> Listing All User Blogs </h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  
    <th>Userblog_id</th>
    <th>User_id</th>
    <th></th>
  </tr>

<% @userblogs.each do |userblog| %>
  <tr>
    <td><%= userblog.title %></td>
    <td><%= userblog.description %></td>
    <td><%= userblog.id %></td>
    <td><%= userblog.user_id %> </td>
     
    <td><%= link_to 'Show', user_userblog_path(userblog.user_id ,userblog.id)  %> </td> 
    <td><%= link_to 'Edit', edit_user_userblog_path(userblog.user_id , userblog.id)  %>  </td>   
    <td><%= link_to 'Destroy', user_userblog_path(userblog.user_id, userblog.id), :method => :delete %> </td>  
  </tr>
<% end %>
</table>

<br />

<%= link_to 'See Users', users_path %> 

app/views/entries/_form.html.haml
= label :entry, :title, 'Title'
= text_field :entry, :title 
%br

= label :entry, :content, 'Description'
= text_field :entry, :content 

%br

app/views/entries/edit.html.haml
%h2 Edit the following entry information for #{@entry.userblog.title} 

= form_tag userblog_entry_path(@entry.userblog.id, @entry.id), :method => :put do

  = render :partial => 'form'      
  = hidden_field :entry, :userblog_id, value: @entry.userblog.id 
  = submit_tag 'Save Changes'

app/views/entries/index.html.erb
<h1>Listing entries for <%=@userblog.user.name %>, Blog Title:  <%=@userblog.title %>   </h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
   
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entries.each do |entry| %>
  <tr>
    <td><%= entry.title %></td>
    <td><%= entry.content %></td>
    
    <td><%= link_to 'Show', userblog_entry_path(@userblog.id, entry.id) %></td>

    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
    <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry', new_userblog_entry_path %> |
<%= link_to 'Back To User Blogs', user_userblogs_path(@userblog.user.id) %> 

app/views/entries/new.html.haml
%h2 Enter a new entry for #{@userblog.title} 
= form_tag userblog_entries_path, :method => :post do
	=render :partial => 'form'  
	= hidden_field :entry, :userblog_id, value: @userblog.id   
	= submit_tag 'Save Changes'

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @entry.title %>
</p>

<p>
  <b>Content:</b>
  <%= @entry.content %>
</p>

<p>
  <b>Userblog:</b>
  <%= @entry.userblog %>
</p>


<%= link_to 'Edit', edit_userblog_entry_path(@entry) %> |
<%= link_to 'Back', userblog_entries_path %>

app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %><br />
    <%= f.number_field :follower_id %>
  </div>
  <div class="field">
    <%= f.label :followed_id %><br />
    <%= f.number_field :followed_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<h1>Listing follows</h1>

<table>
  <tr>
    <th>Follower</th>
    <th>Followed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @follows.each do |follow| %>
  <tr>
    <td><%= follow.follower_id %></td>
    <td><%= follow.followed_id %></td>
    <td><%= link_to 'Show', follow %></td>
    <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
    <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Follower:</b>
  <%= @follow.follower_id %>
</p>

<p>
  <b>Followed:</b>
  <%= @follow.followed_id %>
</p>


<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>

app/views/home/index.html.haml
%h2 This is my blog app
%p Today is
= @now

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title My Blog App!
    = stylesheet_link_tag 'application'

  %body
    
    = yield  

app/views/userblogs/_form.html.haml
= label :userblog, :title, 'Title'
= text_field :userblog, :title 
%br

= label :userblog, :description, 'Description'
= text_field :userblog, :description 

%br

app/views/userblogs/edit.html.haml
%h2 Edit the following blog information for #{@userblog.user.name} 

= form_tag user_userblog_path(@userblog.user_id, @userblog.id), :method => :put do

  = render :partial => 'form'      
  = hidden_field :userblog, :user_id, value: @userblog.user_id 
  = submit_tag 'Save Changes'

app/views/userblogs/index.html.erb
<h1>Listing userblogs for <%=@user.name %> </h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  
    <th>Userblog_id</th>
    <th>User_id</th>
    <th></th>
  </tr>

<% @userblogs.each do |userblog| %>
  <tr>
    <td><%= userblog.title %></td>
    <td><%= userblog.description %></td>
    <td><%= userblog.id %></td>
    <td><%= userblog.user_id %> </td>
     
    <td><%= link_to 'Show', user_userblog_path(@user.id,userblog.id)  %> </td> 
    <td><%= link_to 'Edit', edit_user_userblog_path(@user.id, userblog.id)  %>  </td>   
    <td><%= link_to 'Destroy', user_userblog_path(@user.id, userblog.id), :method => :delete, data: { confirm: 'Are you sure?' } %> </td> 
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Userblog', new_user_userblog_path %> |
<%= link_to 'See User Information', user_path(@user.id)  %> |

app/views/userblogs/new.html.haml
%h2 Enter a new blog for #{@user.name} 
= form_tag user_userblogs_path, :method => :post do
	=render :partial => 'form'  
	= hidden_field :userblog, :user_id, value: @user.id   
	= submit_tag 'Save Changes'

app/views/userblogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @userblog.title %>
</p>

<p>
  <b>Description:</b>
  <%= @userblog.description %>
</p>

<p>
  <b>User:</b>
  <%= @userblog.user.name %>
</p>


<%= link_to 'Edit', edit_user_userblog_path(@user.id, @userblog.id) %> |
<%= link_to 'Back', user_userblogs_path(@userblog.user_id) %> |
<%= link_to 'See Blog Entries', userblog_entries_path(@user.id, @userblog.id) %> 

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', user_path %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th> Location </th>

    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.location %></td>

    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %> |

<%= link_to 'See All User Blogs', alluserblogs_path %> 

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Location:</b>
  <%= @user.location %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'My Blogs', user_userblogs_path(@user.id) %> 